// src/scripts/mods.js
const minecraft = [
  {
    id: "beyond-the-bobber",
    title: "Beyond the Bobber",
    description:
      "**Beyond the Bobber** expands Minecraft’s fishing system into a full-fledged adventure.",
    base: "https://github.com/Mosberg/minecraft/blob/main/beyond-the-bobber/",
    readme: "README.md",
  },
  {
    id: "rarity",
    title: "Rarity",
    description:
      "Introduces rarity tiers to items, making progression more rewarding and loot more exciting.",
    base: "https://github.com/Mosberg/minecraft/blob/main/rarity/",
    readme: "README.md",
    docs: [
      "docs/schemas/rarities.schema.json",
      "docs/info/color-changing.md",
      "docs/info/rarity-frame.md",
      "docs/info/rarity-icons.md",
    ],
    data: ["src/main/resources/data/rarity/rarities.json"],
    models: [
      "src/main/resources/assets/rarity/models/block/common_icon.json",
      "src/main/resources/assets/rarity/models/item/common_icon.json",
    ],
    textures: [
      "src/main/resources/assets/rarity/textures/gui/ancient_frame.png",
      "src/main/resources/assets/rarity/textures/gui/ancient_icon.png",
      "src/main/resources/assets/rarity/textures/gui/celestial_frame.png",
      "src/main/resources/assets/rarity/textures/gui/celestial_icon.png",
      "src/main/resources/assets/rarity/textures/gui/common_frame.png",
      "src/main/resources/assets/rarity/textures/gui/common_icon.png",
      "src/main/resources/assets/rarity/textures/gui/divine_frame_1.png",
      "src/main/resources/assets/rarity/textures/gui/divine_frame_2.png",
      "src/main/resources/assets/rarity/textures/gui/divine_frame_3.png",
      "src/main/resources/assets/rarity/textures/gui/divine_frame_4.png",
      "src/main/resources/assets/rarity/textures/gui/divine_frame_5.png",
      "src/main/resources/assets/rarity/textures/gui/divine_icon_1.png",
      "src/main/resources/assets/rarity/textures/gui/divine_icon_2.png",
      "src/main/resources/assets/rarity/textures/gui/divine_icon_3.png",
      "src/main/resources/assets/rarity/textures/gui/divine_icon_4.png",
      "src/main/resources/assets/rarity/textures/gui/divine_icon_5.png",
      "src/main/resources/assets/rarity/textures/gui/epic_frame.png",
      "src/main/resources/assets/rarity/textures/gui/epic_icon.png",
      "src/main/resources/assets/rarity/textures/gui/legendary_frame.png",
      "src/main/resources/assets/rarity/textures/gui/legendary_icon.png",
      "src/main/resources/assets/rarity/textures/gui/mythic_frame.png",
      "src/main/resources/assets/rarity/textures/gui/mythic_icon.png",
      "src/main/resources/assets/rarity/textures/gui/rare_frame.png",
      "src/main/resources/assets/rarity/textures/gui/rare_icon.png",
      "src/main/resources/assets/rarity/textures/gui/transcendent_frame_1.png",
      "src/main/resources/assets/rarity/textures/gui/transcendent_frame_2.png",
      "src/main/resources/assets/rarity/textures/gui/transcendent_frame_3.png",
      "src/main/resources/assets/rarity/textures/gui/transcendent_frame_4.png",
      "src/main/resources/assets/rarity/textures/gui/transcendent_frame_5.png",
      "src/main/resources/assets/rarity/textures/gui/transcendent_frame_6.png",
      "src/main/resources/assets/rarity/textures/gui/transcendent_frame_7.png",
      "src/main/resources/assets/rarity/textures/gui/transcendent_frame_8.png",
      "src/main/resources/assets/rarity/textures/gui/transcendent_icon_1.png",
      "src/main/resources/assets/rarity/textures/gui/transcendent_icon_2.png",
      "src/main/resources/assets/rarity/textures/gui/transcendent_icon_3.png",
      "src/main/resources/assets/rarity/textures/gui/transcendent_icon_4.png",
      "src/main/resources/assets/rarity/textures/gui/transcendent_icon_5.png",
      "src/main/resources/assets/rarity/textures/gui/transcendent_icon_6.png",
      "src/main/resources/assets/rarity/textures/gui/transcendent_icon_7.png",
      "src/main/resources/assets/rarity/textures/gui/transcendent_icon_8.png",
      "src/main/resources/assets/rarity/textures/gui/trash_frame.png",
      "src/main/resources/assets/rarity/textures/gui/trash_icon.png",
      "src/main/resources/assets/rarity/textures/gui/uncommon_frame.png",
      "src/main/resources/assets/rarity/textures/gui/uncommon_icon.png",
    ],
  },
  {
    id: "rarity-and-relics",
    title: "Rarity & Relics",
    description:
      "This mod combines unique relics with rarity mechanics, adding depth to exploration and loot.",
    base: "https://github.com/Mosberg/minecraft/blob/main/rarity-and-relics/",
    readme: "README.md",
  },
  {
    id: "relics-of-rarity",
    title: "Relics of Rarity",
    description: "",
    base: "https://github.com/Mosberg/minecraft/blob/main/relics-of-rarity/",
    readme: "",
    docs: [
      "schemas/modifiers.schema.json",
      "schemas/nbt.schema.json",
      "schemas/rarities.schema.json",
    ],
  },
];
